alias gs='git status -s'
alias ga='git add '
alias gc='git commit '
alias gd='git diff'
alias go='git checkout '
alias gk='gitk --all'
alias cdccweb='cd projects/contentcentral/contentcentral/Solutions/ContentCentral.Web/ContentCentral.Web'
alias cdcc='cd projects/contentcentral/contentcentral/Solutions'